In [1]:
from trainer import Trainer

In [2]:
env_file = b"C:\Users\sirir\Desktop\University\Master\Semester_3\Data_Science_Semester_Project\Unity_projects\RollerBall_Playground\Builds\RollerBall_Playground.exe".decode("utf-8")

In [3]:
trainer = Trainer(env_file)
trainer.run_steps(100)

INFO:mlagents_envs:Connected new brain:
RollerBallBrain?team=0
c:\Users\sirir\anaconda3\envs\mlagents\lib\site-packages\torch\nn\functional.py:1949: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
c:\Users\sirir\anaconda3\envs\mlagents\lib\site-packages\torch\nn\functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
c:\Users\sirir\Desktop\University\Master\Semester_3\Data_Science_Semester_Project\Unity_projects\RollerBall_Playground\Python_scripts\cnn.py:33: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  out[0, self.softmax_pos] = softmax(input[0, self.softmax_pos])


[[ 0.47746584 -0.07550162]]
[[ 0.47354808 -0.09544773]]
[[ 0.47272813 -0.10192862]]
[[ 0.47275892 -0.10122572]]
[[ 0.4728054  -0.10110381]]
[[ 0.47281882 -0.10077301]]
[[ 0.47289976 -0.10053893]]
[[ 0.47304863 -0.10111637]]
[[ 0.4730394  -0.10138649]]
[[ 0.4729916  -0.10112627]]
[[ 0.4729576  -0.10030057]]
[[ 0.47297686 -0.09937172]]
[[ 0.47297046 -0.09904025]]
[[ 0.47290385 -0.09889677]]
[[ 0.4729149  -0.09869269]]
[[ 0.47297165 -0.09844996]]
[[ 0.4729629  -0.09859101]]
[[ 0.47295424 -0.09836182]]
[[ 0.47301838 -0.09820303]]
[[ 0.47319555 -0.09815854]]
[[ 0.47329012 -0.09799566]]
[[ 0.47326452 -0.09801856]]
[[ 0.4732949  -0.09794599]]
[[ 0.47329134 -0.09765138]]
[[ 0.4732334  -0.09750719]]
[[ 0.47314578 -0.09797615]]
[[ 0.47331172 -0.09896602]]
[[ 0.47342157 -0.09977574]]
[[ 0.4734344  -0.09909268]]
[[ 0.47335777 -0.09875538]]
[[ 0.4733518  -0.09756167]]
[[ 0.4734783  -0.09734993]]
[[ 0.4734575  -0.09724652]]
[[ 0.47344935 -0.09693988]]
[[ 0.47339374 -0.09679442]]
[[ 0.4733338  -0.097

INFO:mlagents_envs:Environment shut down with return code 0 (CTRL_C_EVENT).
